---
name: Maintain node-lts.json

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    name: Is node-lts.json outdated? 🤔
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci --ignore-scripts
      - run: npm run update:node
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: generate-token
        if: ${{ env.HAVE_ECOSPARK_APP_ID == 'true' }}
        env:
          HAVE_ECOSPARK_APP_ID: ${{ secrets.ECOSPARK_APP_ID != '' }}
        with:
          app_id: ${{ secrets.ECOSPARK_APP_ID }}
          private_key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e # v6
        if: ${{ steps.generate-token.outputs.token != '' }}
        with:
          author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
          body: I ran `npm run update:node` 🧑‍💻
          branch: actions/create-node-pr
          commit-message: 'fix(node-lts.json): 🤖 ✨'
          labels: 🤖 bot
          title: 'fix(node-lts.json): update version'
          token: ${{ steps.generate-token.outputs.token }}
