---
name: Maintain node.json

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    name: Is node-lts.json outdated? 🤔
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci --ignore-scripts
      - run: npm run update:node
      - uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        id: generate-token
        if: ${{ env.HAVE_ECOSPARK_APP_ID == 'true' }}
        env:
          HAVE_ECOSPARK_APP_ID: ${{ secrets.ECOSPARK_APP_ID != '' }}
        with:
          app_id: ${{ secrets.ECOSPARK_APP_ID }}
          private_key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5 # v5
        if: ${{ steps.generate-token.outputs.token != '' }}
        with:
          author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
          body: I ran `npm run update:node` 👨‍💻
          branch: actions/create-node-pr
          commit-message: 'fix(node.json): 🤖 ✨'
          labels: 🤖 bot
          title: 'fix(node.json): update version'
          token: ${{ steps.generate-token.outputs.token }}
