---
name: Maintain consistent json sorting

on:
  push:
    branches: [main]
    paths:
      - '**/*.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    name: Is json sorted? 🤔
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci --ignore-scripts
      - run: npm run update:sorting
      - uses: actions/create-github-app-token@v1
        id: app-token
        if: ${{ env.HAVE_ECOSPARK_APP_ID == 'true' }}
        env:
          HAVE_ECOSPARK_APP_ID: ${{ secrets.ECOSPARK_APP_ID != '' }}
        with:
          app-id: ${{ secrets.ECOSPARK_APP_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@9153d834b60caba6d51c9b9510b087acf9f33f83 # v6
        if: ${{ steps.app-token.outputs.token != '' }}
        with:
          author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
          body: I ran `npm run update:sorting` 🧑‍💻
          branch: actions/create-sorting-pr
          commit-message: 'chore(sorting): 🤖 ✨'
          labels: 🤖 bot
          title: 'chore(sorting): apply sorting'
          token: ${{ steps.app-token.outputs.token }}
